package it.unipi.chesspuzzles.server.shared;

public enum BoardStyle {
    GREEN, GLASS, BROWN, NEWSPAPER, WALNUT, SKY, LOLZ, STONE, BASES, MARBLE,
    PURPLE, TRANSLUCENT, METAL, TOURNAMENT, DASH, BLUE, BUBBLEGUM, CHECKERS,
    GRAFFITI, LIGHT, NEON, ORANGE, OVERLAY, PARCHMENT, RED, SAND, TAN
}
