package it.unipi.chesspuzzles.client.shared;

public enum PiecesStyle {
    NEO, WOOD, GLASS, GOTHIC, CLASSIC, METAL, BASES, CLUB, OCEAN, NEWSPAPER,
    SPACE, CASES, CONDAL, MARBLE, BOOK, ALPHA, BUBBLEGUM, DASH, GRAFFITI, LIGHT,
    LUCA, MAYA, MODERN, NATURE, NEON, SKY, TIGERSS, TORUNAMENT, VINTAGE
}